name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on:
      labels: [self-hosted, sal]
      group: Default
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag landing-web:prod
